CREATE TABLE idempotency_keys
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    idempotency_key VARCHAR(255)                            NOT NULL,
    username        VARCHAR(255)                            NOT NULL,
    response_body   VARCHAR(255)                            NOT NULL,
    response_status INTEGER                                 NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_idempotency_keys PRIMARY KEY (id)
);

ALTER TABLE idempotency_keys
    ADD CONSTRAINT uq_idempotency_key_user UNIQUE (idempotency_key, username);

ALTER TABLE audit_logs
ALTER
COLUMN action TYPE VARCHAR(255) USING (action::VARCHAR(255));

ALTER TABLE audit_logs
    ALTER COLUMN action DROP NOT NULL;

ALTER TABLE transactions
ALTER
COLUMN amount TYPE DECIMAL USING (amount::DECIMAL);

ALTER TABLE accounts
ALTER
COLUMN balance TYPE DECIMAL USING (balance::DECIMAL);

ALTER TABLE audit_logs
ALTER
COLUMN details TYPE VARCHAR(255) USING (details::VARCHAR(255));

ALTER TABLE accounts
ALTER
COLUMN iban TYPE VARCHAR(255) USING (iban::VARCHAR(255));

ALTER TABLE audit_logs
ALTER
COLUMN ip_address TYPE VARCHAR(255) USING (ip_address::VARCHAR(255));

ALTER TABLE transactions
ALTER
COLUMN receiver_iban TYPE VARCHAR(255) USING (receiver_iban::VARCHAR(255));

ALTER TABLE app_users
ALTER
COLUMN role TYPE VARCHAR(255) USING (role::VARCHAR(255));

ALTER TABLE transactions
ALTER
COLUMN sender_iban TYPE VARCHAR(255) USING (sender_iban::VARCHAR(255));

ALTER TABLE audit_logs
ALTER
COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE audit_logs
    ALTER COLUMN status DROP NOT NULL;

ALTER TABLE transactions
ALTER
COLUMN status TYPE VARCHAR(255) USING (status::VARCHAR(255));

ALTER TABLE audit_logs
    ALTER COLUMN timestamp DROP NOT NULL;

ALTER TABLE refresh_tokens
    ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE accounts
    ALTER COLUMN version DROP NOT NULL;